[book]
authors = ["ZUO Zhihua"]
language = "zh_CN"
multilingual = false
src = "src"
title = "旅行者2号"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/zoziha/mybook"
site-url = "https://userzuo.netlify.app/"
